### PR TITLE
Manually implement `Default`

### PR DESCRIPTION
**Pull request by pitdicker**
I broke chrono's MSRV with the `unstable-locales` feature in #8.

```
error[E0658]: deriving `Default` on enums is experimental
     --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/pure-rust-locales-0.8.0/src/lib.rs:55118:23
      |
55118 | #[derive(Copy, Clone, Default, PartialEq, Eq, Hash)]
      |                       ^^^^^^^
      |
      = note: see issue #86985 <https://github.com/rust-lang/rust/issues/86985> for more information
      = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This fixes the build for rust 1.61 and adds a CI check for the generated code on rust nightly, beta and 1.61.0.

Can we release this as 0.8.1 to make the CI for chrono green again?

### CODE REVIEW

**Comment by cecton** [comment]
I think you could yank the other and release this one

**Review by cecton — APPROVED** [review]

**Comment by djc** [comment]
Should set the rust-version in the Cargo metadata, I think you won't have to suppress the lint then.

**Comment by pitdicker** [comment]
> Should set the rust-version in the Cargo metadata, I think you won't have to suppress the lint then.

Of course, thank you for reminding me! That is good to set anyway. I'll use the lowest rust version that currently works and supports `rust-version`, 1.56.0

> I think you could yank the other and release this one

Not building with an old rust version doesn't seem quite bad enough for yanking I think.

**Comment by pitdicker** [comment]
Published.
